#ifndef _CONSTANTES_H_
#define _CONSTANTES_H_

const int LARGEUR_FENETRE=800;
const int HAUTEUR_FENETRE=600;
const int TAILLE_LARGEUR_BOUTON = 250;
const int TAILLE_HAUTEUR_BOUTON = 75;
const int NB_ROUTES_MAX=6;
const int TAILLE_ROUTE=40;
const int TAILLE_LARGEUR_FEU = 25;
const int TAILLE_HAUTEUR_FEU = 49;
const int TAILLE_BARRE_PARTIE = 40;
const int ECART_HORIZONTAL_ROUTES=(LARGEUR_FENETRE-TAILLE_ROUTE*NB_ROUTES_MAX/2)/(NB_ROUTES_MAX/2+1);
const int ECART_VERTICAL_ROUTES=(HAUTEUR_FENETRE-TAILLE_ROUTE*NB_ROUTES_MAX/2)/(NB_ROUTES_MAX/2+1);
const int TAILLE_LONGUEUR_VOITURE_ET_POLICE=66;
const int TAILLE_LARGEUR_VOITURE_ET_POLICE=30;
const int TAILLE_LONGUEUR_CAMION=80;
const int TAILLE_LARGEUR_CAMION=30;
const float BASE_VITESSE = 1;

#endif
